### ISSUE TITLE
ESP8266_RTOS_SDK support

### ISSUE THREAD

**Issue by h1aji** [nopnop2002/esp-idf-vs1053#11]
Hi, I was trying to compile your project with ESP8266_RTOS_SDK and it looks ok except errors related to SPI (SPI driver looks to be very different to ESP32).

Any chance you could create another branch and support SDK for ESP8266?
Thanks

**Comment by nopnop2002** [comment]
>Any chance you could create another branch and support SDK for ESP8266?

No.
